// This file is generated by Prismic local builder. Update with care!

export { default as About } from './About'
export { default as Activities } from './Activities'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as ImageAndText } from './ImageAndText'
export { default as Project } from './Project'
